import type { Metadata } from 'next';
import { ArrowRight, Check, Code2, KeyRound, Wallet, Webhook } from 'lucide-react';
import { MarketingHeader, MarketingFooter, SectionHeading, ButtonLink, IconTile } from '../../src/marketing/components';

export const metadata: Metadata = {
  title: 'API Partnerships & Developer Access | Verxor',
  description: 'Learn about Verxor API partner access, authentication, wallet requirements, integration practices and the application process.',
  alternates: { canonical: '/api-partnership' },
  openGraph: { title: 'API Partnerships | Verxor', description: 'Build with Verxor’s supported digital-services API infrastructure.', url: 'https://verxor.com/api-partnership', siteName: 'Verxor', type: 'website' },
};

const schema = { '@context': 'https://schema.org', '@type': 'Service', name: 'Verxor API Partnership', provider: { '@type': 'Organization', name: 'Verxor', url: 'https://verxor.com' }, description: 'API access for eligible developers and businesses, subject to review and plan terms.', url: 'https://verxor.com/api-partnership' };

export default function ApiPartnershipPage() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><MarketingHeader /><main className="mk-partner-page">
    <section className="mk-partner-hero"><div className="mk-container mk-partner-grid"><div><span className="mk-section-eyebrow">FOR DEVELOPERS & BUSINESSES</span><h1>Build your product on a connected digital-services layer.</h1><p>Explore API access for supported services, with documented authentication, wallet-led requests and order-status handling for approved partners.</p><div className="mk-hero-actions"><ButtonLink href="#apply" variant="primary">Apply for API access <ArrowRight size={17} /></ButtonLink><ButtonLink href="#integration" variant="secondary">Explore integration</ButtonLink></div><div className="mk-proof-row"><span><KeyRound size={16} /> Scoped credentials</span><span><Webhook size={16} /> Status & webhooks where supported</span></div></div><div className="mk-code-card"><div className="mk-code-top"><span /><span /><span /><b>Request overview</b></div><pre><code>{'POST /v1/orders\nAuthorization: Bearer YOUR_API_KEY\nContent-Type: application/json\n\n{\n  "service": "supported_product",\n  "reference": "your-unique-reference",\n  "quantity": 1\n}'}</code></pre><div className="mk-code-foot"><ShieldCheckIcon /> Example shape only · use the approved API documentation</div></div></div></section>
    <section className="mk-section"><div className="mk-container"><SectionHeading eyebrow="DESIGNED FOR INTEGRATION" title="The essentials your team needs." description="Access, endpoints and limits are provided according to your approved account and partner plan." /><div className="mk-benefit-grid mk-api-benefits"><article><IconTile icon={KeyRound} tone="blue" /><h3>Authentication</h3><p>Use the credential format, scopes, rotation rules and secure storage guidance supplied for your approved plan.</p></article><article><IconTile icon={Wallet} tone="green" /><h3>Wallet requirements</h3><p>Keep sufficient available balance for the products and fees in your plan. Reconcile requests against transaction references and ledger records.</p></article><article><IconTile icon={Webhook} tone="violet" /><h3>Statuses & callbacks</h3><p>Handle pending, success and failure states. Use signed callbacks and idempotent processing where supported by the documented integration.</p></article></div></div></section>
    <section className="mk-partner-dark" id="integration"><div className="mk-container mk-partner-dark-grid"><div><span className="mk-section-eyebrow">INTEGRATION FLOW</span><h2>From approved access to a reliable workflow.</h2><p>Production integrations should validate every request, store secrets server-side, handle retries safely and reconcile final transaction status.</p></div><div className="mk-integration-steps"><article><span>01</span><div><b>Application review</b><p>Share your business, use case and technical contact.</p></div></article><article><span>02</span><div><b>Credentials & docs</b><p>Approved partners receive the applicable credentials and documentation.</p></div></article><article><span>03</span><div><b>Test, reconcile, launch</b><p>Test error handling and status reconciliation before production use.</p></div></article></div></div></section>
    <section className="mk-section"><div className="mk-container mk-share-grid"><div><span className="mk-section-eyebrow">PARTNER COMMERCIALS</span><h2>A transparent 50/50 net-margin arrangement for eligible partners.</h2><p>Where the written partner agreement offers a 50/50 share, the calculation starts with the customer revenue collected for an eligible transaction and subtracts the applicable upstream provider wholesale cost. The remaining net margin is then split equally between Verxor and the approved partner.</p><div className="mk-share-equation"><span>Customer revenue</span><b>−</b><span>Provider wholesale cost</span><b>=</b><strong>Net margin → split 50 / 50</strong></div><p className="mk-small-note">The exact transaction scope, refunds, reversals, fees, settlement schedule, eligible products and reporting method must be defined in the signed agreement. This is not a guarantee of revenue or profit; a share applies only where expressly approved in writing.</p></div><div className="mk-share-card"><span className="mk-share-card-label">ILLUSTRATIVE EXAMPLE</span><div><span>Customer revenue</span><b>₦1,000</b></div><div><span>Wholesale cost</span><b>− ₦700</b></div><div className="mk-share-net"><span>Remaining net margin</span><b>₦300</b></div><div className="mk-share-split"><span>Verxor share</span><strong>₦150</strong></div><div className="mk-share-split"><span>Partner share</span><strong>₦150</strong></div><p>Example only. Excludes any additional fees, refunds, taxes or adjustments that the written agreement may specify.</p></div></div></section>
    <section className="mk-section mk-application-section" id="apply"><div className="mk-container mk-application-grid"><div><span className="mk-section-eyebrow">START A CONVERSATION</span><h2>Apply for API partnership.</h2><p>Applications are reviewed before access is issued. Prepare a short description of your product, expected use case and technical needs.</p><ul><li><Check size={16} /> Business or project details</li><li><Check size={16} /> Intended services and expected volume</li><li><Check size={16} /> Technical contact and integration plan</li></ul></div><div className="mk-application-card"><IconTile icon={Code2} tone="blue" /><h3>Partner applications</h3><p>To avoid losing your information, the application intake must be connected to Verxor’s approved submission endpoint before this form can collect or transmit personal data.</p><div className="mk-form-readiness"><span /> Application intake: awaiting backend connection</div><ButtonLink href="/workspace" variant="primary">Continue to Verxor <ArrowRight size={17} /></ButtonLink><p className="mk-small-note">No API credentials are issued automatically. Access is subject to review, security checks and plan terms.</p></div></div></section>
  </main><MarketingFooter /></>;
}

function ShieldCheckIcon() { return <Check size={14} />; }
