import type { Metadata } from 'next';
import { ArrowRight, Check, Globe2, Layers3, ShieldCheck, Wallet } from 'lucide-react';
import { MarketingHeader, MarketingFooter, SectionHeading, ButtonLink, IconTile } from '../../src/marketing/components';

export const metadata: Metadata = {
  title: 'White-label Child Panels & Reseller Program | Verxor',
  description: 'Learn how Verxor child panels work, including branding, custom domains, retail pricing rules, wallet synchronization and onboarding.',
  alternates: { canonical: '/child-panels' },
  openGraph: { title: 'Child Panels & Resellers | Verxor', description: 'Explore a branded digital-services panel powered by Verxor.', url: 'https://verxor.com/child-panels', siteName: 'Verxor', type: 'website' },
};

const schema = { '@context': 'https://schema.org', '@type': 'Service', name: 'Verxor Child Panel Program', provider: { '@type': 'Organization', name: 'Verxor', url: 'https://verxor.com' }, description: 'White-label digital-services child panels for approved reseller businesses.', url: 'https://verxor.com/child-panels' };

export default function ChildPanelsPage() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><MarketingHeader /><main className="mk-partner-page">
    <section className="mk-partner-hero mk-reseller-hero"><div className="mk-container mk-partner-grid"><div><span className="mk-section-eyebrow">FOR RESELLERS & BUSINESS OWNERS</span><h1>Your brand on the front. Verxor powering the service layer.</h1><p>Apply to run a branded child panel for supported digital services, with platform operations and provider integrations managed through Verxor’s core system.</p><div className="mk-hero-actions"><ButtonLink href="#apply" variant="primary">Explore panel applications <ArrowRight size={17} /></ButtonLink><ButtonLink href="#how-it-works" variant="secondary">How child panels work</ButtonLink></div><div className="mk-proof-row"><span><Layers3 size={16} /> White-label experience</span><span><ShieldCheck size={16} /> Tenant boundaries</span></div></div><div className="mk-reseller-visual"><div className="mk-reseller-window"><div className="mk-reseller-window-head"><img src="/brand/verxor-logo.svg" alt="" /><span>Your brand panel</span><span className="mk-preview-pill">CONCEPT</span></div><div className="mk-reseller-welcome"><span className="mk-mini-label">RESELLER WORKSPACE</span><h2>Run your digital services business.</h2><p>Illustrative child-panel dashboard preview.</p></div><div className="mk-reseller-metrics"><div><span>Wallet status</span><b>Synced through platform</b></div><div><span>Retail pricing</span><b>Within approved rules</b></div><div><span>Services</span><b>Based on enabled catalog</b></div></div></div></div></div></section>
    <section className="mk-section"><div className="mk-container"><SectionHeading eyebrow="YOUR BUSINESS, CONNECTED" title="A clearer operating model for resellers." description="Child panels are separate tenant experiences. The exact features, fees and controls depend on the approved commercial plan." /><div className="mk-benefit-grid"><article><IconTile icon={Layers3} tone="blue" /><h3>Branded customer experience</h3><p>Present enabled services under your approved panel branding. Brand assets and domain requirements are confirmed during onboarding.</p></article><article><IconTile icon={Globe2} tone="violet" /><h3>Custom domain mapping</h3><p>Use a supported custom domain after DNS ownership, configuration, SSL and platform validation requirements are met.</p></article><article><IconTile icon={Wallet} tone="green" /><h3>Wallet synchronization</h3><p>Child balances and transactions are handled through the platform’s defined ledger and synchronization rules. Reconciliation and corrections remain auditable.</p></article></div></div></section>
    <section className="mk-partner-dark" id="how-it-works"><div className="mk-container mk-partner-dark-grid"><div><span className="mk-section-eyebrow">HOW IT WORKS</span><h2>Clear boundaries. Shared infrastructure.</h2><p>Verxor operates the core service layer. The child-panel owner manages their customer-facing business within the permissions and pricing rules of the agreement.</p></div><div className="mk-integration-steps"><article><span>01</span><div><b>Apply and qualify</b><p>Provide your business details, use case and expected service volume.</p></div></article><article><span>02</span><div><b>Configure the panel</b><p>Agree branding, domain, enabled catalog, fees and wallet arrangements.</p></div></article><article><span>03</span><div><b>Operate within the rules</b><p>Retail pricing must meet applicable Verxor floor prices; access and features are enforced server-side.</p></div></article></div></div></section>
    <section className="mk-section"><div className="mk-container mk-pricing-rules"><div><span className="mk-section-eyebrow">PRICING & COMMERCIALS</span><h2>Set retail pricing within your approved margin.</h2><p>Verxor defines floor prices for applicable services. A child panel may set retail prices at or above the relevant floor, subject to the product and commercial agreement. Provider wholesale costs and master credentials are not exposed to child tenants.</p></div><div className="mk-rule-card"><div><span>Verxor floor price</span><b>Minimum permitted price</b></div><div className="mk-rule-line" /><div><span>Your approved retail price</span><b>Equal to or above floor</b></div><div className="mk-rule-check"><Check size={17} /> Validated by the platform</div></div></div></section>
    <section className="mk-section mk-application-section" id="apply"><div className="mk-container mk-application-grid"><div><span className="mk-section-eyebrow">BECOME A RESELLER</span><h2>Tell us about your panel.</h2><p>Applications are reviewed to confirm fit, operating model and required configuration before a child tenant is created.</p><ul><li><Check size={16} /> Business and customer segment</li><li><Check size={16} /> Requested services and expected volume</li><li><Check size={16} /> Branding and domain plans</li></ul></div><div className="mk-application-card"><IconTile icon={Layers3} tone="violet" /><h3>Child-panel applications</h3><p>Application intake must be connected to Verxor’s approved submission endpoint before this page can collect or transmit your details.</p><div className="mk-form-readiness"><span /> Application intake: awaiting backend connection</div><ButtonLink href="/workspace" variant="primary">Continue to Verxor <ArrowRight size={17} /></ButtonLink><p className="mk-small-note">Approval, fees, onboarding time, available services and domain setup are confirmed individually. A child panel does not receive master provider credentials.</p></div></div></section>
  </main><MarketingFooter /></>;
}
