import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Gift, Headphones, Instagram, KeyRound, MessageSquare, Package, Phone, Search, ShieldCheck, Users, WalletCards, Zap } from 'lucide-react';
import { Card, PrimaryButton, SectionHeader } from './components/ui';

export type ServiceView = 'rental' | 'boost' | 'boost-orders' | 'accounts' | 'account-orders' | 'number-orders' | 'rewards' | 'affiliate' | 'alerts' | 'settings' | 'feedback' | 'privacy';

const catalog = [
  { id: 'rental', title: 'Rent a number', eyebrow: 'DEDICATED LINE', description: 'Choose a private number for the duration you need.', icon: Phone },
  { id: 'boost', title: 'Social & music growth', eyebrow: 'SMM SERVICES', description: 'Browse available growth services with clear order tracking.', icon: Instagram },
  { id: 'accounts', title: 'Buy accounts', eyebrow: 'DIGITAL ACCOUNTS', description: 'Review available inventory and delivery information.', icon: Users },
] as const;

export function ServicesPage({ open }: { open: (view: ServiceView) => void }) {
  return <><section className="page-intro"><p className="eyebrow">VERXOR SERVICES</p><h1>What are you looking for?</h1><p>Choose a service and complete each step with clear pricing and status.</p></section><div className="service-stack">{catalog.map(({id,title,eyebrow,description,icon:Icon})=><button className="product-card" key={id} onClick={()=>open(id)}><span className="product-icon"><Icon size={20}/></span><span><em>{eyebrow}</em><strong>{title}</strong><small>{description}</small></span><ArrowRight size={17}/></button>)}</div><SectionHeader eyebrow="ORDERS" title="Your activity" /><div className="service-stack"><button className="product-card" onClick={()=>open('number-orders')}><span className="product-icon"><Package size={20}/></span><span><strong>Number orders</strong><small>View your verification orders</small></span><ArrowRight size={17}/></button><button className="product-card" onClick={()=>open('boost-orders')}><span className="product-icon"><Clock3 size={20}/></span><span><strong>Boost orders</strong><small>Track social service delivery</small></span><ArrowRight size={17}/></button></div></>;
}

function ServiceLayout({ title, eyebrow, description, onBack, children }: { title:string; eyebrow:string; description:string; onBack:()=>void; children:React.ReactNode }) {
  return <><button className="back-button" onClick={onBack}><ArrowLeft size={17}/> Back</button><section className="page-intro compact-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></section>{children}</>;
}

export function ServicePage({ view, onBack }: { view: ServiceView; onBack:()=>void }) {
  if(view==='rental') return <ServiceLayout title="Rent a number" eyebrow="DEDICATED LINE" description="Select a country, duration and available number." onBack={onBack}><div className="search-box"><Search size={18}/><input placeholder="Search country" /></div><div className="option-list">{['United States · +1','United Kingdom · +44','Canada · +1'].map(country=><Card className="option-row" key={country}><div className="option-main"><span className="product-icon"><Phone size={18}/></span><div><strong>{country}</strong><small>Voice + SMS available</small></div></div><button className="small-button">Select</button></Card>)}</div></ServiceLayout>;
  if(view==='boost') return <ServiceLayout title="Social & music growth" eyebrow="SMM SERVICES" description="Choose a service, review its delivery terms and place your order." onBack={onBack}><div className="search-box"><Search size={18}/><input placeholder="Search services" /></div><div className="option-list">{['Instagram engagement','TikTok views','YouTube views','Music streams'].map((name,i)=><Card className="service-line" key={name}><div><em>POPULAR</em><strong>{name}</strong><small>Clear delivery status · {i+1}–3 hours typical</small></div><span className="price-tag">From ₦500</span></Card>)}</div><PrimaryButton>Continue <ArrowRight size={17}/></PrimaryButton></ServiceLayout>;
  if(view==='accounts') return <ServiceLayout title="Buy accounts" eyebrow="ACCOUNT INVENTORY" description="Browse current inventory and review delivery information before checkout." onBack={onBack}><div className="option-list">{['Social account · Standard','Creator account · Premium','Business account · Premium'].map(name=><Card className="service-line" key={name}><div><em>AVAILABLE</em><strong>{name}</strong><small>Delivery details shown before payment</small></div><span className="price-tag">View</span></Card>)}</div></ServiceLayout>;
  if(view==='number-orders') return <ServiceLayout title="Number orders" eyebrow="ORDERS" description="Keep track of your verification number activity." onBack={onBack}><EmptyOrders icon={<KeyRound size={18}/>} title="No number orders" text="Your completed and active verification orders will appear here." /></ServiceLayout>;
  if(view==='boost-orders') return <ServiceLayout title="Boost orders" eyebrow="ORDERS" description="Track delivery and status for your growth orders." onBack={onBack}><EmptyOrders icon={<Package size={18}/>} title="No boost orders" text="Orders you place will appear here with their current status." /></ServiceLayout>;
  if(view==='account-orders') return <ServiceLayout title="Account orders" eyebrow="ORDERS" description="Review your account purchase history." onBack={onBack}><EmptyOrders icon={<Users size={18}/>} title="No account orders" text="Your account purchases will appear here." /></ServiceLayout>;
  if(view==='rewards') return <ServiceLayout title="Rewards" eyebrow="REWARDS" description="See your earned rewards and available benefits." onBack={onBack}><Card className="reward-card"><Gift size={22}/><div><small>Total rewards</small><strong>₦0.00</strong></div></Card><Card className="info-card"><CheckCircle2 size={18}/><div><strong>Keep using Verxor</strong><p>Eligible rewards will be reflected here automatically.</p></div></Card></ServiceLayout>;
  if(view==='affiliate') return <ServiceLayout title="Affiliate" eyebrow="REFERRALS" description="Share your referral link and track eligible rewards." onBack={onBack}><Card className="referral-card"><small>Your referral link</small><strong>verxor.com/ref/your-link</strong><button className="copy-button">Copy link</button></Card><div className="metric-grid"><Card><small>Referrals</small><strong>0</strong></Card><Card><small>Earned</small><strong>₦0.00</strong></Card></div></ServiceLayout>;
  if(view==='alerts') return <ServiceLayout title="Alerts" eyebrow="NOTIFICATIONS" description="Important account and order updates appear here." onBack={onBack}><EmptyOrders icon={<MessageSquare size={18}/>} title="You're all caught up" text="New security, payment and order updates will appear here." /></ServiceLayout>;
  if(view==='settings') return <ServiceLayout title="Settings" eyebrow="PREFERENCES" description="Control how Verxor works for you." onBack={onBack}><Card className="settings-list">{[['Theme','Light & dark mode'],['Notifications','Order and account updates'],['Security','Password and account protection']].map(([a,b])=><div className="setting-row" key={a}><div><strong>{a}</strong><small>{b}</small></div><ArrowRight size={17}/></div>)}</Card></ServiceLayout>;
  if(view==='feedback') return <ServiceLayout title="Feedback" eyebrow="SUPPORT" description="Tell us what we can improve." onBack={onBack}><Card className="form-card"><label htmlFor="feedback">Your feedback</label><textarea id="feedback" rows={6} placeholder="Tell us what you think…" /><PrimaryButton><Headphones size={18}/> Send feedback</PrimaryButton></Card></ServiceLayout>;
  return <ServiceLayout title="Privacy policy" eyebrow="LEGAL" description="How Verxor handles account and service information." onBack={onBack}><Card className="legal-card"><h3>Privacy at Verxor</h3><p>We aim to collect only the information needed to provide, secure and improve the service. Account information and transaction data are handled according to the applicable service and security requirements.</p><h3>Security</h3><p>Use a strong password and keep your account credentials private. Contact support if you notice activity you do not recognize.</p></Card></ServiceLayout>;
}

function EmptyOrders({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <Card className="empty-card page-empty"><div className="empty-icon">{icon}</div><strong>{title}</strong><p>{text}</p></Card>; }
