import type { ReactNode } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Gift, Headphones, Instagram, KeyRound, MessageSquare, Package, Phone, Search, Users } from 'lucide-react';
import { Card, PrimaryButton, SectionHeader } from './components/ui';
import './service-pages.css';

export type ServiceView = 'services' | 'virtual-numbers' | 'rental' | 'boost' | 'boost-orders' | 'accounts' | 'account-orders' | 'number-orders' | 'rewards' | 'affiliate' | 'alerts' | 'settings' | 'feedback' | 'privacy';

const catalog = [
  { id: 'virtual-numbers' as const, title: 'Virtual Numbers', eyebrow: 'OTP VERIFICATION', description: 'Choose a country and service, then select an available number.', icon: Phone },
  { id: 'rental' as const, title: 'Rent a Line', eyebrow: 'DEDICATED LINE', description: 'Choose a private number and the rental period you need.', icon: Clock3 },
  { id: 'boost' as const, title: 'SMM Boost', eyebrow: 'SOCIAL GROWTH', description: 'Browse growth services with clear order tracking.', icon: Instagram },
  { id: 'accounts' as const, title: 'Buy Accounts', eyebrow: 'ACCOUNT INVENTORY', description: 'Review available inventory and delivery information.', icon: Users },
];

export function ServicesPage({ open }: { open: (view: ServiceView) => void }) {
  return <><section className="page-intro"><p className="eyebrow">VERXOR SERVICES</p><h1>Services</h1><p>Choose a service to get started.</p></section><div className="service-stack">{catalog.map(({id,title,eyebrow,description,icon:Icon})=><button className="product-card" key={id} onClick={()=>open(id)}><span className="product-icon"><Icon size={20}/></span><span><em>{eyebrow}</em><strong>{title}</strong><small>{description}</small></span><ArrowRight size={17}/></button>)}</div></>;
}

function ServiceLayout({ title, eyebrow, description, onBack, children }: { title:string; eyebrow:string; description:string; onBack:()=>void; children:ReactNode }) { return <><button className="back-button" onClick={onBack}><ArrowLeft size={17}/> Back</button><section className="page-intro compact-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></section>{children}</>; }

export function ServicePage({ view, onBack }: { view: Exclude<ServiceView, 'services'>; onBack:()=>void }) {
  if(view==='virtual-numbers') return <ServiceLayout title="Virtual Numbers" eyebrow="OTP VERIFICATION" description="Select a country and service to see available numbers."><div className="search-box"><Search size={18}/><input placeholder="Search country or service" aria-label="Search country or service" /></div><div className="option-list">{['United States · +1','United Kingdom · +44','Canada · +1','India · +91'].map(country=><Card className="option-row" key={country}><div className="option-main"><span className="product-icon"><Phone size={18}/></span><div><strong>{country}</strong><small>Numbers available</small></div></div><button className="small-button">View</button></Card>)}</div><SectionHeader eyebrow="ORDERS" title="Number history" action={<button className="text-button">View all</button>} /></ServiceLayout>;
  if(view==='rental') return <ServiceLayout title="Rent a Line" eyebrow="DEDICATED LINE" description="Select a country, duration and available number." onBack={onBack}><div className="search-box"><Search size={18}/><input placeholder="Search country" aria-label="Search country" /></div><div className="option-list">{['United States · +1','United Kingdom · +44','Canada · +1'].map(country=><Card className="option-row" key={country}><div className="option-main"><span className="product-icon"><Phone size={18}/></span><div><strong>{country}</strong><small>Voice + SMS available</small></div><button className="small-button">Select</button></div></Card>)}</div></ServiceLayout>;
  if(view==='boost') return <ServiceLayout title="SMM Boost" eyebrow="SOCIAL GROWTH" description="Choose a service, review delivery terms and place your order." onBack={onBack}><div className="search-box"><Search size={18}/><input placeholder="Search services" aria-label="Search services" /></div><div className="option-list">{['Instagram engagement','TikTok views','YouTube views','Music streams'].map(name=><Card className="service-line" key={name}><div><em>AVAILABLE</em><strong>{name}</strong><small>Delivery status shown on every order</small></div><span className="price-tag">View</span></Card>)}</div><PrimaryButton>Continue <ArrowRight size={17}/></PrimaryButton></ServiceLayout>;
  if(view==='accounts') return <ServiceLayout title="Buy Accounts" eyebrow="ACCOUNT INVENTORY" description="Browse current inventory and review delivery information." onBack={onBack}><div className="option-list">{['Social account · Standard','Creator account · Premium','Business account · Premium'].map(name=><Card className="service-line" key={name}><div><em>AVAILABLE</em><strong>{name}</strong><small>Delivery details shown before payment</small></div><span className="price-tag">View</span></Card>)}</div></ServiceLayout>;
  if(view==='number-orders') return <ServiceLayout title="Number orders" eyebrow="ORDERS" description="Keep track of your verification number activity." onBack={onBack}><EmptyOrders icon={<KeyRound size={18}/>} title="No number orders" text="Your completed and active verification orders will appear here." /></ServiceLayout>;
  if(view==='boost-orders') return <ServiceLayout title="Boost orders" eyebrow="ORDERS" description="Track delivery and status for your growth orders." onBack={onBack}><EmptyOrders icon={<Package size={18}/>} title="No boost orders" text="Orders you place will appear here with their current status." /></ServiceLayout>;
  if(view==='account-orders') return <ServiceLayout title="Account orders" eyebrow="ORDERS" description="Review your account purchase history." onBack={onBack}><EmptyOrders icon={<Users size={18}/>} title="No account orders" text="Your account purchases will appear here." /></ServiceLayout>;
  if(view==='rewards') return <ServiceLayout title="Rewards" eyebrow="REWARDS" description="See your earned rewards and available benefits." onBack={onBack}><Card className="reward-card"><Gift size={22}/><div><small>Total rewards</small><strong>₦0.00</strong></div></Card><Card className="info-card"><CheckCircle2 size={18}/><div><strong>Rewards</strong><p>Eligible rewards will be reflected here automatically.</p></div></Card></ServiceLayout>;
  if(view==='affiliate') return <ServiceLayout title="Affiliate" eyebrow="REFERRALS" description="Share your referral link and track eligible rewards." onBack={onBack}><Card className="referral-card"><small>Your referral link</small><strong>verxor.com/ref/your-link</strong><button className="copy-button">Copy link</button></Card></ServiceLayout>;
  if(view==='alerts') return <ServiceLayout title="Notifications" eyebrow="ACCOUNT" description="Important account and order updates appear here." onBack={onBack}><EmptyOrders icon={<MessageSquare size={18}/>} title="You're all caught up" text="New security, payment and order updates will appear here." /></ServiceLayout>;
  if(view==='settings') return <ServiceLayout title="Security" eyebrow="ACCOUNT SECURITY" description="Keep your account protected." onBack={onBack}><Card className="settings-list">{[['Password','Update your password'],['PIN','Manage your transaction PIN'],['Sessions','Review active sessions']].map(([a,b])=><div className="setting-row" key={a}><div><strong>{a}</strong><small>{b}</small></div><ArrowRight size={17}/></div>)}</Card></ServiceLayout>;
  if(view==='feedback') return <ServiceLayout title="Contact Support" eyebrow="SUPPORT" description="Tell us what you need help with." onBack={onBack}><Card className="form-card"><label htmlFor="feedback">Message</label><textarea id="feedback" rows={6} placeholder="Describe the issue…" /><PrimaryButton><Headphones size={18}/> Send message</PrimaryButton></Card></ServiceLayout>;
  return <ServiceLayout title="Help Center" eyebrow="SUPPORT" description="Find guidance for your account and Verxor services." onBack={onBack}><Card className="legal-card"><h3>Getting started</h3><p>Choose a service, review the available options and confirm your order before payment.</p><h3>Account security</h3><p>Keep your password and PIN private. Contact support if you notice activity you do not recognize.</p></Card></ServiceLayout>;
}

function EmptyOrders({icon,title,text}:{icon:ReactNode;title:string;text:string}) { return <Card className="empty-card page-empty"><div className="empty-icon">{icon}</div><strong>{title}</strong><p>{text}</p></Card>; }
